name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10', '3.12', '3.14', 'pypy3.11']
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Compile check
        run: python -m compileall speedtest.py

      - name: Live speedtest
        run: python speedtest.py --simple

      - name: Source bind failure test
        run: python tests/scripts/source.py

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Lint
        run: |
          pip install flake8
          flake8 speedtest.py
